package com.zrh.model.menu;

public class Action_permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_permission.action_permission_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer actionPermissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_permission.action_permission_name
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private String actionPermissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_permission.action_permission_code
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer actionPermissionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_permission.action_permission_id
     *
     * @return the value of action_permission.action_permission_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getActionPermissionId() {
        return actionPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_permission.action_permission_id
     *
     * @param actionPermissionId the value for action_permission.action_permission_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setActionPermissionId(Integer actionPermissionId) {
        this.actionPermissionId = actionPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_permission.action_permission_name
     *
     * @return the value of action_permission.action_permission_name
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public String getActionPermissionName() {
        return actionPermissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_permission.action_permission_name
     *
     * @param actionPermissionName the value for action_permission.action_permission_name
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setActionPermissionName(String actionPermissionName) {
        this.actionPermissionName = actionPermissionName == null ? null : actionPermissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_permission.action_permission_code
     *
     * @return the value of action_permission.action_permission_code
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getActionPermissionCode() {
        return actionPermissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_permission.action_permission_code
     *
     * @param actionPermissionCode the value for action_permission.action_permission_code
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setActionPermissionCode(Integer actionPermissionCode) {
        this.actionPermissionCode = actionPermissionCode;
    }
}