package com.zrh.model.menu;

public class Action {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.name
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.href
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.permission_v
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer permissionV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.id
     *
     * @return the value of action.id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.id
     *
     * @param id the value for action.id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.name
     *
     * @return the value of action.name
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.name
     *
     * @param name the value for action.name
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.href
     *
     * @return the value of action.href
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.href
     *
     * @param href the value for action.href
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.permission_v
     *
     * @return the value of action.permission_v
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getPermissionV() {
        return permissionV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.permission_v
     *
     * @param permissionV the value for action.permission_v
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setPermissionV(Integer permissionV) {
        this.permissionV = permissionV;
    }
}