package com.zrh.model.menu;

public class Left_menu_action {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column left_menu-action.left-menu_id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer leftMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column left_menu-action.action_idaction
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer actionIdaction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column left_menu-action.left-menu_id
     *
     * @return the value of left_menu-action.left-menu_id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getLeftMenuId() {
        return leftMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column left_menu-action.left-menu_id
     *
     * @param leftMenuId the value for left_menu-action.left-menu_id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setLeftMenuId(Integer leftMenuId) {
        this.leftMenuId = leftMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column left_menu-action.action_idaction
     *
     * @return the value of left_menu-action.action_idaction
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getActionIdaction() {
        return actionIdaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column left_menu-action.action_idaction
     *
     * @param actionIdaction the value for left_menu-action.action_idaction
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setActionIdaction(Integer actionIdaction) {
        this.actionIdaction = actionIdaction;
    }
}