package com.zrh.model.menu;

public class Left_menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column left-menu.id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column left-menu.name
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column left-menu.p_id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column left-menu.menu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer menuFloor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column left-menu.id
     *
     * @return the value of left-menu.id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column left-menu.id
     *
     * @param id the value for left-menu.id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column left-menu.name
     *
     * @return the value of left-menu.name
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column left-menu.name
     *
     * @param name the value for left-menu.name
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column left-menu.p_id
     *
     * @return the value of left-menu.p_id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column left-menu.p_id
     *
     * @param pId the value for left-menu.p_id
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column left-menu.menu_floor
     *
     * @return the value of left-menu.menu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getMenuFloor() {
        return menuFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column left-menu.menu_floor
     *
     * @param menuFloor the value for left-menu.menu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setMenuFloor(Integer menuFloor) {
        this.menuFloor = menuFloor;
    }
}