package com.zrh.model.menu;

public class Menu_floor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_floor.idmenu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer idmenuFloor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_floor.idmenu_floor
     *
     * @return the value of menu_floor.idmenu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getIdmenuFloor() {
        return idmenuFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_floor.idmenu_floor
     *
     * @param idmenuFloor the value for menu_floor.idmenu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setIdmenuFloor(Integer idmenuFloor) {
        this.idmenuFloor = idmenuFloor;
    }
}