package com.zrh.model.menu;

public class Permission_left_menu_role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission-left_menu-role.permission
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    private Integer permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission-left_menu-role.permission
     *
     * @return the value of permission-left_menu-role.permission
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission-left_menu-role.permission
     *
     * @param permission the value for permission-left_menu-role.permission
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
}