package com.zrh.model.menu;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private String rolePermission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_permission
     *
     * @return the value of role.role_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public String getRolePermission() {
        return rolePermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_permission
     *
     * @param rolePermission the value for role.role_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setRolePermission(String rolePermission) {
        this.rolePermission = rolePermission == null ? null : rolePermission.trim();
    }
}