package com.zrh.model.menu;

public class Role_menuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_menu_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer menuMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer roleRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_menu_id
     *
     * @return the value of role_menu.menu_menu_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getMenuMenuId() {
        return menuMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_menu_id
     *
     * @param menuMenuId the value for role_menu.menu_menu_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setMenuMenuId(Integer menuMenuId) {
        this.menuMenuId = menuMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_role_id
     *
     * @return the value of role_menu.role_role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getRoleRoleId() {
        return roleRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_role_id
     *
     * @param roleRoleId the value for role_menu.role_role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setRoleRoleId(Integer roleRoleId) {
        this.roleRoleId = roleRoleId;
    }
}