package com.zrh.model.menu;

public class Role_action_permission extends Role_action_permissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_action_permission.permission_code
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private String permissionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_action_permission.permission_code
     *
     * @return the value of role_action_permission.permission_code
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_action_permission.permission_code
     *
     * @param permissionCode the value for role_action_permission.permission_code
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }
}