package com.zrh.model.menu;

public class Role_action_permissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_action_permission.action_action_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer actionActionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_action_permission.role_role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    private Integer roleRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_action_permission.action_action_id
     *
     * @return the value of role_action_permission.action_action_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getActionActionId() {
        return actionActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_action_permission.action_action_id
     *
     * @param actionActionId the value for role_action_permission.action_action_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setActionActionId(Integer actionActionId) {
        this.actionActionId = actionActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_action_permission.role_role_id
     *
     * @return the value of role_action_permission.role_role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public Integer getRoleRoleId() {
        return roleRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_action_permission.role_role_id
     *
     * @param roleRoleId the value for role_action_permission.role_role_id
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    public void setRoleRoleId(Integer roleRoleId) {
        this.roleRoleId = roleRoleId;
    }
}