package com.zrh.dao;

import com.zrh.model.menu.Action;

public interface ActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insert(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insertSelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    Action selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int updateByPrimaryKeySelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int updateByPrimaryKey(Action record);
}