package com.zrh.dao;

import com.zrh.model.menu.Action_permission;

public interface Action_permissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int deleteByPrimaryKey(Integer actionPermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int insert(Action_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int insertSelective(Action_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    Action_permission selectByPrimaryKey(Integer actionPermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int updateByPrimaryKeySelective(Action_permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_permission
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int updateByPrimaryKey(Action_permission record);
}