package com.zrh.dao;

import com.zrh.model.menu.Actions;

public interface ActionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int insert(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int insertSelective(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    Actions selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int updateByPrimaryKeySelective(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Fri Jun 21 08:25:49 CST 2019
     */
    int updateByPrimaryKey(Actions record);
}