package com.zrh.dao;

import com.zrh.model.menu.Left_menu_action;

public interface Left_menu_actionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left_menu-action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insert(Left_menu_action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left_menu-action
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insertSelective(Left_menu_action record);
}