package com.zrh.dao;

import com.zrh.model.menu.Left_menu;

public interface Left_menuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left-menu
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left-menu
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insert(Left_menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left-menu
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insertSelective(Left_menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left-menu
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    Left_menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left-menu
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int updateByPrimaryKeySelective(Left_menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table left-menu
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int updateByPrimaryKey(Left_menu record);
}