package com.zrh.dao;

import com.zrh.model.menu.Menu_floor;

public interface Menu_floorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int deleteByPrimaryKey(Integer idmenuFloor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insert(Menu_floor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_floor
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insertSelective(Menu_floor record);
}