package com.zrh.dao;

import com.zrh.model.menu.Permission_left_menu_role;

public interface Permission_left_menu_roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission-left_menu-role
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int deleteByPrimaryKey(Integer permission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission-left_menu-role
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insert(Permission_left_menu_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission-left_menu-role
     *
     * @mbggenerated Sun Jun 16 15:18:06 CST 2019
     */
    int insertSelective(Permission_left_menu_role record);
}